modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
authors="Ravynik" #optional

modId="untraveledmod" #mandatory
version="1.0" #mandatory
displayName="Untraveled Mod" #mandatory

credits="Thanks for this example mod goes to Java" #optional
description='''
This is my mod. I hope you like it.
'''
